#!/bin/bash
# =====================================================================================
# wasi-sandwiched-build.sh
#
# The tool must apply the SAME conjuncts as the detector, on the SAME code path.
# It does not link a library and it does not re-type the arithmetic: it COMPILES A
# VERBATIM BYTE SLICE of extraction-exact.swift alongside its own I/O layer.
#
#   lines 1..END_LINE of extraction-exact.swift  =  every declaration, up to but not
#   including that program's own SECTION 11 MAIN. runCorpus(), computeShortfall(),
#   v2Out(), v3Step(), v3InvertStart(), U256/I256/SInt and the JSON scanner all live
#   in that range, and this tool calls them, unmodified, by their own names.
#
# The slice digest is computed HERE and compiled in, so the binary can state which
# bytes of law it carries and a stranger can re-derive that digest in one command:
#
#   sed -n "1,${END_LINE}p" extraction-exact.swift | shasum -a 256
# =====================================================================================
set -u -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

SRC=extraction-exact.swift
SLICE=.core-detector.swift
PIN=.core-pin.swift
# THE BOUNDARY IS DERIVED FROM A NAMED MARKER, NEVER TYPED AS A LINE NUMBER.
#
# It was typed as 2535 in THREE separate files — this script, wasi-sandwiched-one-law.sh
# and reproduce/validate.sh — so any additive edit to the law was a four-file change and
# three of the four would have gone on quoting a stale number. That is the same defect this
# study records elsewhere: a constant duplicated across consumers is a constant that drifts.
# The marker "SECTION 11 — MAIN" is what actually separates the declarations from the
# program's own top-level code, so the boundary is read off that. The structural check that
# follows is unchanged and still REFUSES if what it finds is not a closing brace followed by
# a rule — deriving the number does not remove the check, it removes the retyping.
# THE PATTERN IS ANCHORED AND CARRIES NO DOT, AND THAT IS A LOCALE FIX, NOT A STYLE ONE.
# The marker's dash is an EM DASH — three bytes in UTF-8. This harness and these scripts
# run with LANG and LC_ALL unset, so awk is in the C locale and `.` matches ONE BYTE: the
# old pattern /SECTION 11 . MAIN/ matched interactively, where the shell has a UTF-8
# locale, and matched NOTHING where it actually runs. The guard below then refused a
# correct tree — a false refusal, which is the always-red half of the same defect as a
# false pass. Anchored on the line start with no metacharacter over the dash, this
# returns the same line in both locales, verified in both.
END_LINE=$(awk '/^\/\/ SECTION 11 /{print NR-3; exit}' "$SRC")
[ -n "$END_LINE" ] || { echo "BUILD_REFUSED  SECTION 11 MAIN marker not found in $SRC"; exit 3; }

[ -f "$SRC" ] || { echo "BUILD_REFUSED  detector source absent: $SRC"; exit 3; }

# The boundary is asserted nowhere: it is CHECKED. That line must close referenceFigures()
# and 2503 must open the detector's own MAIN. If the detector moves, this refuses to build
# rather than slicing law in half.
b1=$(sed -n "${END_LINE}p" "$SRC")
b2=$(sed -n "$((END_LINE + 2))p" "$SRC")
if [ "$b1" != "}" ] || ! printf '%s' "$b2" | grep -q '^// ====='; then
  echo "BUILD_REFUSED  slice boundary moved: line ${END_LINE} = [$b1]  line $((END_LINE+2)) = [$b2]"
  exit 3
fi
# Nothing after the boundary may be reachable from the slice, and nothing before it may be
# a top-level STATEMENT (Swift allows those only in main.swift). Both directions checked.
if sed -n "1,${END_LINE}p" "$SRC" | grep -nE '^(emit|kv|section|flush|exit|print)\(' >/dev/null; then
  echo "BUILD_REFUSED  the slice carries a top-level statement"
  exit 3
fi

# NOTHING IN THE SLICE MAY REFERENCE A SYMBOL DEFINED AFTER IT. The check above catches a
# top-level STATEMENT in the slice; it does not catch a slice line that CALLS opt() or
# flag(), both of which live in MAIN, below the boundary. That compiles here — this file
# has MAIN — and fails inside the tool that gets only the slice, with "cannot find 'flag'
# in scope" in a file nobody edited. Measured: it happened, and the build error named
# wasi-sandwiched rather than the law that broke it. Comments are stripped before the
# match so that prose describing the rule does not trip it.
if sed -n "1,${END_LINE}p" "$SRC" | sed 's|//.*||' | grep -qE '\b(opt|flag)\('; then
  echo "BUILD_REFUSED  the slice calls opt() or flag(), which are defined below the boundary"
  echo "               move the argv read into MAIN and have the slice read a global instead"
  exit 3
fi

sed -n "1,${END_LINE}p" "$SRC" > "$SLICE" || exit 3
SLICE_SHA=$(shasum -a 256 "$SLICE" | awk '{print $1}')
SLICE_BYTES=$(wc -c < "$SLICE" | tr -d ' ')
SRC_SHA=$(shasum -a 256 "$SRC" | awk '{print $1}')
SRC_BYTES=$(wc -c < "$SRC" | tr -d ' ')
SELF_SHA=$(shasum -a 256 wasi-sandwiched.swift | awk '{print $1}')

cat > "$PIN" <<PINEOF
// GENERATED BY wasi-sandwiched-build.sh — do not edit. Every value here was COMPUTED
// at build time by shasum(1) over the named file. None is asserted.
let CORE_SLICE_SHA256   = "$SLICE_SHA"
let CORE_SLICE_BYTES    = "$SLICE_BYTES"
let CORE_SLICE_LINES    = "1..$END_LINE"
let CORE_SOURCE_NAME    = "$SRC"
let CORE_SOURCE_SHA256  = "$SRC_SHA"
let CORE_SOURCE_BYTES   = "$SRC_BYTES"
let TOOL_SOURCE_SHA256  = "$SELF_SHA"
let BUILD_UTC           = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
PINEOF

xcrun swiftc -O -swift-version 5 "$SLICE" "$PIN" wasi-sandwiched.swift -o wasi-sandwiched 2>&1
rc=$?
if [ $rc -ne 0 ]; then echo "BUILD_FAILED rc=$rc"; exit $rc; fi

echo "BUILT      wasi-sandwiched  ($(wc -c < wasi-sandwiched | tr -d ' ') bytes)"
echo "core slice ${SRC} lines 1..${END_LINE}  ${SLICE_BYTES} bytes  sha256 ${SLICE_SHA}"
echo "re-derive  sed -n '1,${END_LINE}p' ${SRC} | shasum -a 256"
