#!/bin/bash
# =====================================================================================
# wasi-exposure-build.sh
#
# The pre-trade check must apply the SAME arithmetic as the realised-loss detector, on
# the SAME code path. It does not link a library and it does not re-type the arithmetic:
# it COMPILES A VERBATIM BYTE SLICE of extraction-exact.swift alongside its own I/O
# layer — the identical slice wasi-sandwiched-build.sh cuts, from the identical marker.
#
# THE BOUNDARY IS DERIVED FROM A NAMED MARKER, NEVER TYPED AS A LINE NUMBER, for the
# reason wasi-sandwiched-build.sh records: a constant duplicated across consumers is a
# constant that drifts. This file is the fourth consumer of that boundary and it would
# have been the fourth stale copy.
#
# AND NO LAW DIGEST IS PINNED HERE EITHER. An earlier version refused unless the slice
# hashed to the digest the published page carried; on 2026-09-08 the detector grew from
# 2,688 lines to 3,011 in a neighbouring session and that refusal fired over a change
# that broke nothing. Whether this tool and wasi-sandwiched carry the SAME law is a
# RELATION between two binaries, and wasi-exposure-one-law.sh measures it by reading
# both. A relation survives the law growing; a literal does not.
#
#   sed -n "1,${END_LINE}p" extraction-exact.swift | shasum -a 256
# =====================================================================================
set -u -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

SRC=extraction-exact.swift
SLICE=.core-detector-exposure.swift
PIN=.core-pin-exposure.swift

[ -f "$SRC" ] || { echo "BUILD_REFUSED  detector source absent: $SRC"; exit 3; }
# THE PATTERN IS ANCHORED AND CARRIES NO DOT, AND THAT IS A LOCALE FIX, NOT A STYLE ONE.
# The marker's dash is an EM DASH — three bytes in UTF-8. This harness and these scripts
# run with LANG and LC_ALL unset, so awk is in the C locale and `.` matches ONE BYTE: the
# old pattern /SECTION 11 . MAIN/ matched interactively, where the shell has a UTF-8
# locale, and matched NOTHING where it actually runs. The guard below then refused a
# correct tree — a false refusal, which is the always-red half of the same defect as a
# false pass. Anchored on the line start with no metacharacter over the dash, this
# returns the same line in both locales, verified in both.
END_LINE=$(awk '/^\/\/ SECTION 11 /{print NR-3; exit}' "$SRC")
[ -n "$END_LINE" ] || { echo "BUILD_REFUSED  SECTION 11 MAIN marker not found in $SRC"; exit 3; }

# The boundary is asserted nowhere: it is CHECKED. That line must close referenceFigures()
# and two lines on must open the detector's own MAIN. If the detector moves in a way the
# marker does not describe, this REFUSES rather than slicing a law in half.
b1=$(sed -n "${END_LINE}p" "$SRC")
b2=$(sed -n "$((END_LINE + 2))p" "$SRC")
if [ "$b1" != "}" ] || ! printf '%s' "$b2" | grep -q '^// ====='; then
  echo "BUILD_REFUSED  slice boundary moved: line ${END_LINE} = [$b1]  line $((END_LINE+2)) = [$b2]"
  exit 3
fi
# Nothing before the boundary may be a top-level STATEMENT (Swift allows those only in
# main.swift), or @main in the tool cannot compile. Checked, not assumed.
if sed -n "1,${END_LINE}p" "$SRC" | grep -nE '^(emit|kv|section|flush|exit|print)\(' >/dev/null; then
  echo "BUILD_REFUSED  the slice carries a top-level statement"
  exit 3
fi
# NOTHING IN THE SLICE MAY REFERENCE A SYMBOL DEFINED AFTER IT — opt() and flag() live in
# MAIN, below the boundary, and a slice line that calls one compiles in the detector and
# fails in the tool with "cannot find 'flag' in scope" in a file nobody edited. Comments
# are stripped first so that prose describing this rule does not trip it.
if sed -n "1,${END_LINE}p" "$SRC" | sed 's|//.*||' | grep -qE '\b(opt|flag)\('; then
  echo "BUILD_REFUSED  the slice calls opt() or flag(), which are defined below the boundary"
  exit 3
fi

sed -n "1,${END_LINE}p" "$SRC" > "$SLICE" || exit 3
SLICE_SHA=$(shasum -a 256 "$SLICE" | awk '{print $1}')
SLICE_BYTES=$(wc -c < "$SLICE" | tr -d ' ')
SRC_SHA=$(shasum -a 256 "$SRC" | awk '{print $1}')
SRC_BYTES=$(wc -c < "$SRC" | tr -d ' ')
SELF_SHA=$(shasum -a 256 wasi-exposure.swift | awk '{print $1}')

# THE PIN CARRIES ONLY WHAT THIS BUILD MEASURED, and it is the SAME set of constants
# wasi-sandwiched-build.sh emits — so a harness that already knows how to build one tool
# builds the other with no special case.
cat > "$PIN" <<PINEOF
// GENERATED BY wasi-exposure-build.sh — do not edit. Every value here was COMPUTED at
// build time by shasum(1) over the named file. None is asserted.
let CORE_SLICE_SHA256   = "$SLICE_SHA"
let CORE_SLICE_BYTES    = "$SLICE_BYTES"
let CORE_SLICE_LINES    = "1..$END_LINE"
let CORE_SOURCE_NAME    = "$SRC"
let CORE_SOURCE_SHA256  = "$SRC_SHA"
let CORE_SOURCE_BYTES   = "$SRC_BYTES"
let TOOL_SOURCE_SHA256  = "$SELF_SHA"
let BUILD_UTC           = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
PINEOF

xcrun swiftc -O -swift-version 5 "$SLICE" "$PIN" wasi-exposure.swift -o wasi-exposure 2>&1
rc=$?
if [ $rc -ne 0 ]; then echo "BUILD_FAILED rc=$rc"; exit $rc; fi

echo "BUILT       wasi-exposure  ($(wc -c < wasi-exposure | tr -d ' ') bytes)"
echo "law         ${SRC} lines 1..${END_LINE}  ${SLICE_BYTES} bytes  sha256 ${SLICE_SHA}"
echo "same_law_as wasi-sandwiched — measured by wasi-exposure-one-law.sh, not claimed here"
echo "re-derive   sed -n '1,${END_LINE}p' ${SRC} | shasum -a 256"
